version: '3.8'
  
services:
  app:
    image: smart-roast-backend:v1.2
    container_name: sm_backend
    env_file:
      - .env.prod
    network_mode: host
    ports:
      - "5432:5432"
      - "3000:3000"
    
