DROP TABLE users CASCADE;

CREATE TABLE users (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  password VARCHAR(2000) NOT NULL,
  salt VARCHAR(2000) NOT NULL);
